gateways:
  local:
    connection:
      type: duckdb
      database: sqlmesh.db
    state_connection:
      type: postgres
      host: db
      port: 5432
      user: sqlmesh
      password: sqlmesh
      database: sqlmesh

# The default_gateway key specifies the default gateway SQLMesh should use when executing commands.
default_gateway: local

# Model specific configuration like table format, SQL dialect, start date for backfill etc.
model_defaults:
  dialect: spark2

# Git configuration for syncing models and configurations
git:
  enabled: true                    # Enable Git integration
  repo_url: git@github.com:huseyinyener/sqlmesh.git # Git repository URL (use SSH for secure access)
  branch: main                     # Branch to pull from
  pull_frequency: interval           # Options: manual or interval (e.g., every 5m, every 1h)
  sync_on_startup: true            # Whether to sync on startup automatically
